INSERT INTO MEMBER (email, pw, name, tel, address, date) VALUES('tnehfdl2011@gmail.com', '12345', '최수빈', '010-2042-1992', '서울시 강북구 삼양동', sysdate)
INSERT INTO MEMBER (email, pw, name, tel, address, date) VALUES('tnehfdl2004@naver.com', '23456', '수빈','010-2042-1992', '서울시 강북구 삼양동', sysdate)
INSERT INTO MEMBER (email, pw, name, tel, address, date) VALUES('tnehfdl2002@hanmail.net', '34567', '수비니', '010-2042-1992', '서울시 강북구 삼양동', sysdate)
INSERT INTO MEMBER (email, pw, name, tel, address, date) VALUES('tnehfdl2002@yahoo.co.kr', '45678', '숩쵸이', '010-2042-1992', '서울시 강북구 삼양동', sysdate)
INSERT INTO MEMBER (email, pw, name, tel, address, date) VALUES('ferendevelop@gmail.com', '56789', '정성태', '010-4083-8192', '서울시 강서구 마곡동', sysdate)

	
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이' ,'gd_origin.png', '소주', '1,200원', '무학소주', '16.5', '360ml(Bottle)', 10, '2009-10-14','72시간 산소숙성과 10단계 여과로 더 부드러워진 좋은데이 좋은데이의 시그니처 도수 16.9도는 유지하면서 부드러운 목넘김과 깔끔한 맛이 더욱 새로워 졌습니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이 1929', 'gd_1929.png', '소주', '1,200원', '무학소주', '15.9', '360ml(Bottle)', 10, '2009-10-14','아침이 깨끗한 소주 최고급 원료를 엄선하여 첫맛은 부드럽고 끝 맛은 깔끔한 어떤 음식과도 조화롭게 잘 어울리는 제품')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('딱!좋은데이', 'very_gd.png', '소주', '1,200원', '무학소주', '16.9', '360ml(Bottle)', 10, '2009-10-14','첫맛부터 끝 맛까지 부드러운 맛 ‘딱! 좋은데이’는 가장 순수한 상태의 소주의 맛을 구현하기 위해 당류의 사용을 절제하고 소량의 첨가물과 고도화된 기술 섬세한 여과과정을 통해 만들어져, 첫맛부터 끝 맛까지 균일하게 청량하고 부드러운 맛을 느끼실 수 있습니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이컬러시리즈 복숭아', 'gd_peach.png', '소주', '1,200원', '무학소주', '13.5', '360ml(Bottle)', 10, '2019-08-14','순하게 상큼달콤 좋은데이 복숭아')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이컬러시리즈 석류',  'gd_pom.png', '소주', '1,200원', '무학소주', '13.5', '360ml(Bottle)', 10, '2019-08-14','순하게 새콤하게 좋은데이 석류')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이컬러시리즈 블루베리', 'gd_blue.png', '소주', '1,200원', '무학소주', '13.5', '360ml(Bottle)', 10, '2019-08-14','순하게 달콤하게 좋은데이 블루베리')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이컬러시리즈 자몽',  'gd_grape.png', '소주', '1,200원', '무학소주', '13.5', '360ml(Bottle)', 10, '2019-08-14','순하게 상큼새콤 좋은데이 자몽')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이컬러시리즈 유자',  'gd_citron.png', '소주', '1,200원', '무학소주', '13.5', '360ml(Bottle)', 10, '2019-08-14','순하게 상큼하게 좋은데이 유자')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('좋은데이깔라만시', 'gd_cala.png', '소주', '1,200원', '무학소주', '12.5', '360ml(Bottle)', 10, '2013-10-14','천연 깔라만시 과즙이 들어가 더 깔끔하고 상큼하게~! 곡물을 발효시켜 증류한 주정에 깔라만시 원액을 담아 상큼한 맛이 특징')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('대선', 'daesun.png', '소주', '1,200원', '대선주조', '16.9', '360ml(Bottle)', 10, '2009-10-14','알코올 도수 16.9도 부드럽고 깔끔한 소주맛!')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('C1', 'c1.png', '소주', '1,200원', '대선주조', '19.0', '360ml(Bottle)', 10, '2009-10-14','소주의 참맛을 살린 소주다운 소주')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('참이슬 Fresh', 'real_fresh.png', '소주', '1,200원', '하이트진로', '17.0', '360ml(Bottle)', 10, '2010-10-14','대한민국 청정지역에서만 선별된 대나무 숯으로 4번 걸러 더 깨끗한 목넘김과 이슬형태의 곡선 라벨로 더욱 트렌디해진 참이슬fresh 입니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('참이슬 Original', 'real_original.png', '소주', '1,200원', '하이트진로', '20.1', '360ml(Bottle)', 10, '2010-10-14','대한민국 소주의 정통성을 지켜온 정통소주로서 대나무 숯으로 4번 걸러, 숙취 유발 물질을 깨끗하게 제거하고 레귤러 대비 높은 도수로, 깊고 진한 맛을 구현해 진짜 소주의 참맛을 아는 소비자들에게 꾸준히 사랑받는 제품입니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('일품 진로1924', 'jinro.png', '소주', '1,200원', '하이트진로', '25.0', '360ml(Bottle)', 10, '2009-10-14', '증류 초기와 말기에 나오는 원액은 과감히 버리고 향과 풍미가 뛰어난 증류 중간 원액만을 사용하였습니다. 100% 순쌀증류원액을 냉동여과공법으로 잡미와 불순물을 제거하여 깔끔한 맛과 부드러운 목넘김으로 대한민국 소비자들이 선호하는 은은한 맛의 여운과 깊은 풍미를 완성하였습니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('처음처럼 순한', 'first_weak.png', '소주', '1,200원', '롯데주류', '16.5', '360ml(Bottle)', 10, '2009-10-14','순한 처음처럼은 부드러운 처음처럼보다 0.5도가 낮은 저도소주로 젋은 감각에 맞춰 개발되었습니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('처음처럼 진한', 'first_strong.png', '소주', '1,200원', '롯데주류', '20.0', '360ml(Bottle)', 10, '2009-10-14','처음처럼 진한은 알칼리 환원수에 오크통에서 10년간 숙성시킨 증류주 원액을 블렌딩하여 부드럽고 깊은 맛이 나도록 만든 소주입니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('대장부', 'bigman.png', '소주', '1,500원', '롯데주류', '25.0', '375ml(Bottle)', 10, '2009-10-14','대장부는 100% 국산쌀의 외피를 도정한 속살을 원료로 하여 15도 이하의 저온에서 발효와 숙성을 거쳐 깊은 향과 부드러운 목넘김을 구현한 제품입니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('잎새주', 'leaf.png', '소주', '1,200원', '보해양조', '19.0', '360ml(Bottle)', 10, '2009-10-14','몸을 생각하는 소주  일반적으로 소주는 인공조미료를 사용하여 역취를 없애기도 합니다. 잎새주는 100% 자연에서 추출한 감미료만을 사용했습니다. 잎새주는 당과 나트륨, MSG를 넣지 않은 소주입니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('꿀꺽', 'ggul.png', '소주', '1,200원', '보해양조', '9.2', '360ml(Bottle)', 10, '2019-10-01','달달한 술이 생각날땐 꿀꺽!')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('한라산21', 'hilitesign.png', '소주', '1,200원', '한라산소주', '21.0', '360ml(Bottle)', 10, '2013-04-14','제주산 쌀을 원료로 한 증류식 원액첨가,  화산암반수로 빚어내다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('HITE', 'hite.png', '맥주', '1,700원', '진로하이트', '4.5', '500ml', 10, '2009-10-14','숙성에서부터 여과까지 생산 전 공정을 맥주가 얼기 직전, 영하의 온도에서 제조하여 시원하고 청량한 페일라거 맥주 본연의 맛을 극대화')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('TERRA', 'terra.png', '맥주', '1,700원', '진로하이트', '4.6', '500ml', 10, '2009-10-14','세계 공기질 부문 1위인 호주에서도 청정하기로 유명한 땅, 골든 트라이앵글에서 자란 청정맥아를 사용')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('클라우드', 'kloud.png', '맥주', '1,700원', '롯데주류', '5.0', '500ml', 10, '2009-10-14','클라우드는 오리지널 그래비티 공법을 적용해 풍부한 맛과 풍부한 거품을 자랑하는 프리미엄 리얼맥주입니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('피츠 수퍼클리어', 'fitz.png', '맥주', '1,700원', '롯데주류', '4.5', '500ml', 10, '2009-10-14','피츠 수퍼클리어는 언제,어디서,누구와 함께해도 부담없이 즐길 수 있습니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('CASS', 'cass.png', '맥주', '1,700원', 'OB맥주', '4.5', '500ml', 10, '2009-10-14','젊음의 No.1 맥주 톡 쏘고 상쾌한 맛으로 대한민국에서 가장 사랑 받는 카스')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('조니워커 블루라벨' ,'johnniwalkerblue.png', '양주', '150,000원', 'John walker & Sons', '40.0', '700ml', 10, '2000-10-14','국내에서는 미군에 의해 널리 알려진 제품의 하나였던 조니워커는 가문의 명성과 품질을 상징하는 위스키로 40개 이상의 몰트위스키와 그레인을 섞어 만든다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('조니워커 플레티넘', 'johnniwalkerplatinum.png', '양주', '280,000원', 'John walker & Sons', '40.0', '700ml', 10, '2000-10-14','이 위스키는 하이랜드 몰트를 중심으로 약 40여종의 몰트와 그레인을 블랜딩 하는데 레드레이블 (RED LABEL)은 12년 숙성된 고급품이며, 올드하모니 (OLD HARMONY)는 부드럽고 경쾌한 맛, 전체적으로 부드러운 풍미가 특징이다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('발렌타인 21Y', 'ballentines21.png', '양주', '180,000원', 'George Ballantine and Son', '43.0', '700ml', 10, '1990-10-14','발렌타인의 특징은 향보다는 질감이라 할 수 있습니다.  숙성하면 촉감이 더 좋아지지만,  20년 정도가 지나면 향을 잃기 시작합니다. 따라서 최상의 부드러운 스카치 위스키라 자신할 수 있습니다.')
INSERT INTO GOODS (gd_name, gd_img, gd_kinds, gd_price, gd_maker, gd_alcohol, gd_vol, gd_stock, gd_startday, gd_discription) VALUES('발렌타인 30Y', 'ballentines30.png', '양주', '260,000원', 'George Ballantine and Son', '43.0', '700ml', 10, '1990-10-14','30년산은 스카치의 최고봉으로 정평이 나 있는 주옥의 고주古酒, 30년의 세월이 갈고닦은 위스키 숙성의 극치의 맛을 즐길 수 있다.')


INSERT INTO SHOPPINGCART (sb_num, sb_user, gd_amount) VALUES(1, 'tnehfdl2011@gmail.com', 5)
INSERT INTO SHOPPINGCART (sb_num, sb_user, gd_amount) VALUES(5, 'tnehfdl2011@gmail.com', 3)
INSERT INTO SHOPPINGCART (sb_num, sb_user, gd_amount) VALUES(20, 'ferendevelop@gmail.com', 1)
INSERT INTO SHOPPINGCART (sb_num, sb_user, gd_amount) VALUES(15, 'ferendevelop@gmail.com', 2)
			
	
INSERT INTO DELIVERY (del_name, del_img, del_kinds, del_price, del_maker, del_status) VALUES('참이슬 Fresh','irin_goods.png','소주','1,500원','하이트진로','배송중')
INSERT INTO DELIVERY (del_name, del_img, del_kinds, del_price, del_maker, del_status) VALUES('처음처럼','suzy_goods.png','소주','1,500원','롯데주류','배송중')
INSERT INTO DELIVERY (del_name, del_img, del_kinds, del_price, del_maker, del_status) VALUES('좋은데이','son_goods.png','소주','1,500원','무학소주','배송 준비중')
INSERT INTO DELIVERY (del_name, del_img, del_kinds, del_price, del_maker, del_status) VALUES('카스','cass_goods.jpg','맥주','3,500원','OB맥주','주문 접수')
INSERT INTO DELIVERY (del_name, del_img, del_kinds, del_price, del_maker, del_status) VALUES('하이트','yeona_goods.jpg','맥주','3,500원','하이트진로','배송 준비중')


INSERT INTO BUYED (buy_name, buy_img, buy_kinds, buy_price, buy_maker, buy_status) VALUES('참이슬 Fresh','irin_goods.png','소주','1,500원','하이트진로','배송 완료')
INSERT INTO BUYED (buy_name, buy_img, buy_kinds, buy_price, buy_maker, buy_status) VALUES('처음처럼','suzy_goods.png','소주','1,500원','롯데주류','배송 완료')
INSERT INTO BUYED (buy_name, buy_img, buy_kinds, buy_price, buy_maker, buy_status) VALUES('좋은데이','son_goods.png','소주','1,500원','무학소주','배송 완료')
INSERT INTO BUYED (buy_name, buy_img, buy_kinds, buy_price, buy_maker, buy_status) VALUES('카스','cass_goods.jpg','맥주','3,500원','OB맥주','배송 완료')
INSERT INTO BUYED (buy_name, buy_img, buy_kinds, buy_price, buy_maker, buy_status) VALUES('하이트','yeona_goods.jpg','맥주','3,500원','하이트진로','배송 완료')
	

INSERT INTO QNA (post_sub, post_contant, post_writer, post_date) VALUES('맛있어요.', '룰루랄랄라~' ,'최수빈' ,sysdate)
INSERT INTO QNA (post_sub, post_contant, post_writer, post_date) VALUES('맛없어요.', '룰루랄랄라~' ,'정성태' ,sysdate)
INSERT INTO QNA (post_sub, post_contant, post_writer, post_date) VALUES('역시 Soolfarm', '룰루랄랄라~' ,'최수빈' ,sysdate)
INSERT INTO QNA (post_sub, post_contant, post_writer, post_date) VALUES('여기서만 사게 되네요.', '룰루랄랄라~' ,'정성태' ,sysdate)
INSERT INTO QNA (post_sub, post_contant, post_writer, post_date) VALUES('저렴한 술은 Soolfarm', '룰루랄랄라~' ,'최수빈' ,sysdate)


INSERT INTO BANNER (name, start_dttm, end_dttm, img_name, scription) VALUES('발렌타인',sysdate, null, 'ballentines_banner.png', '발렌타인의 특징은 향보다는 질감이라 할 수 있습니다.')
INSERT INTO BANNER (name, start_dttm, end_dttm, img_name, scription) VALUES('조니워커',sysdate, null, 'johnniwalker_banner.png', '국내에서는 미군에 의해 널리 알려진 제품')
INSERT INTO BANNER (name, start_dttm, end_dttm, img_name, scription) VALUES('처음처럼',sysdate, null, 'first_banner.png', '저도소주로 젋은 감각에 맞춰 개발되었습니다.')
INSERT INTO BANNER (name, start_dttm, end_dttm, img_name, scription) VALUES('좋은데이',sysdate, null, 'goodday_banner.png', '72시간 산소숙성과 10단계 여과로 더 부드러워진 좋은데이')
INSERT INTO BANNER (name, start_dttm, end_dttm, img_name, scription) VALUES('참이슬',sysdate, null, 'true_banner.png', '대한민국 청정지역에서만 선별된 대나무 숯으로 4번 걸러 더 깨끗한 목넘김')


INSERT INTO ADD (NAME, IMG_NAME) VALUES('좋은데이', 'aa.jpg')
INSERT INTO ADD (NAME, IMG_NAME) VALUES('처음처럼', 'bb.jpg')
INSERT INTO ADD (NAME, IMG_NAME) VALUES('참이슬', 'cc.jpg')